#
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: cn.edu.xaut.quanyou.Model

server:
  port: 8080
  servlet:
   context-path: /api


alibaba:
  cloud:
   oss:
    endpoint:  https://oss-cn-hangzhou.aliyuncs.com
spring:
  application:
    name: quanyou
#  profiles:
#    active: div 使用sawgger配置类来防止接口泄露
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learning
    username: root
    password: 123456
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
knife4j:
  enable: true
  basic:
      enable: true
      # 用户名
      username: DareLucem
      # 密码
      password: 155029
  openapi:
    title: Knife4j官方文档
    description: "`这是友圈的接口测试"
    email: thisistheway0429@outlook.com
    concat: Dare Lucem
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 测试模块
        api-rule: package
        api-rule-resources:
          "cn.edu.xaut.quanyou.Controller"